/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef DistSTO_H
#define DistSTO_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "DistSTO_types.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class DistSTOIf {
 public:
  virtual ~DistSTOIf() {}
  virtual void ping() = 0;
  virtual void do_rpc(DoRpcResponse& _return, const int64_t objid, const int64_t op, const std::vector<std::string> & opargs) = 0;
  virtual int64_t lock(const int32_t tuid, const std::vector<std::string> & titems, const bool may_duplicate_items_, const std::vector<bool> & preceding_duplicate_read_) = 0;
  virtual bool check(const int32_t tuid, const std::vector<std::string> & titems, const bool may_duplicate_items_, const std::vector<bool> & preceding_duplicate_read_) = 0;
  virtual void install(const int32_t tuid, const int64_t tid, const std::vector<std::string> & write_values) = 0;
  virtual void abort(const int32_t tuid) = 0;
};

class DistSTOIfFactory {
 public:
  typedef DistSTOIf Handler;

  virtual ~DistSTOIfFactory() {}

  virtual DistSTOIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(DistSTOIf* /* handler */) = 0;
};

class DistSTOIfSingletonFactory : virtual public DistSTOIfFactory {
 public:
  DistSTOIfSingletonFactory(const boost::shared_ptr<DistSTOIf>& iface) : iface_(iface) {}
  virtual ~DistSTOIfSingletonFactory() {}

  virtual DistSTOIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(DistSTOIf* /* handler */) {}

 protected:
  boost::shared_ptr<DistSTOIf> iface_;
};

class DistSTONull : virtual public DistSTOIf {
 public:
  virtual ~DistSTONull() {}
  void ping() {
    return;
  }
  void do_rpc(DoRpcResponse& /* _return */, const int64_t /* objid */, const int64_t /* op */, const std::vector<std::string> & /* opargs */) {
    return;
  }
  int64_t lock(const int32_t /* tuid */, const std::vector<std::string> & /* titems */, const bool /* may_duplicate_items_ */, const std::vector<bool> & /* preceding_duplicate_read_ */) {
    int64_t _return = 0;
    return _return;
  }
  bool check(const int32_t /* tuid */, const std::vector<std::string> & /* titems */, const bool /* may_duplicate_items_ */, const std::vector<bool> & /* preceding_duplicate_read_ */) {
    bool _return = false;
    return _return;
  }
  void install(const int32_t /* tuid */, const int64_t /* tid */, const std::vector<std::string> & /* write_values */) {
    return;
  }
  void abort(const int32_t /* tuid */) {
    return;
  }
};


class DistSTO_ping_args {
 public:

  DistSTO_ping_args(const DistSTO_ping_args&);
  DistSTO_ping_args& operator=(const DistSTO_ping_args&);
  DistSTO_ping_args() {
  }

  virtual ~DistSTO_ping_args() throw();

  bool operator == (const DistSTO_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const DistSTO_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DistSTO_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DistSTO_ping_pargs {
 public:


  virtual ~DistSTO_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DistSTO_ping_result {
 public:

  DistSTO_ping_result(const DistSTO_ping_result&);
  DistSTO_ping_result& operator=(const DistSTO_ping_result&);
  DistSTO_ping_result() {
  }

  virtual ~DistSTO_ping_result() throw();

  bool operator == (const DistSTO_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const DistSTO_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DistSTO_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DistSTO_ping_presult {
 public:


  virtual ~DistSTO_ping_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _DistSTO_do_rpc_args__isset {
  _DistSTO_do_rpc_args__isset() : objid(false), op(false), opargs(false) {}
  bool objid :1;
  bool op :1;
  bool opargs :1;
} _DistSTO_do_rpc_args__isset;

class DistSTO_do_rpc_args {
 public:

  DistSTO_do_rpc_args(const DistSTO_do_rpc_args&);
  DistSTO_do_rpc_args& operator=(const DistSTO_do_rpc_args&);
  DistSTO_do_rpc_args() : objid(0), op(0) {
  }

  virtual ~DistSTO_do_rpc_args() throw();
  int64_t objid;
  int64_t op;
  std::vector<std::string>  opargs;

  _DistSTO_do_rpc_args__isset __isset;

  void __set_objid(const int64_t val);

  void __set_op(const int64_t val);

  void __set_opargs(const std::vector<std::string> & val);

  bool operator == (const DistSTO_do_rpc_args & rhs) const
  {
    if (!(objid == rhs.objid))
      return false;
    if (!(op == rhs.op))
      return false;
    if (!(opargs == rhs.opargs))
      return false;
    return true;
  }
  bool operator != (const DistSTO_do_rpc_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DistSTO_do_rpc_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DistSTO_do_rpc_pargs {
 public:


  virtual ~DistSTO_do_rpc_pargs() throw();
  const int64_t* objid;
  const int64_t* op;
  const std::vector<std::string> * opargs;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _DistSTO_do_rpc_result__isset {
  _DistSTO_do_rpc_result__isset() : success(false) {}
  bool success :1;
} _DistSTO_do_rpc_result__isset;

class DistSTO_do_rpc_result {
 public:

  DistSTO_do_rpc_result(const DistSTO_do_rpc_result&);
  DistSTO_do_rpc_result& operator=(const DistSTO_do_rpc_result&);
  DistSTO_do_rpc_result() {
  }

  virtual ~DistSTO_do_rpc_result() throw();
  DoRpcResponse success;

  _DistSTO_do_rpc_result__isset __isset;

  void __set_success(const DoRpcResponse& val);

  bool operator == (const DistSTO_do_rpc_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const DistSTO_do_rpc_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DistSTO_do_rpc_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _DistSTO_do_rpc_presult__isset {
  _DistSTO_do_rpc_presult__isset() : success(false) {}
  bool success :1;
} _DistSTO_do_rpc_presult__isset;

class DistSTO_do_rpc_presult {
 public:


  virtual ~DistSTO_do_rpc_presult() throw();
  DoRpcResponse* success;

  _DistSTO_do_rpc_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _DistSTO_lock_args__isset {
  _DistSTO_lock_args__isset() : tuid(false), titems(false), may_duplicate_items_(false), preceding_duplicate_read_(false) {}
  bool tuid :1;
  bool titems :1;
  bool may_duplicate_items_ :1;
  bool preceding_duplicate_read_ :1;
} _DistSTO_lock_args__isset;

class DistSTO_lock_args {
 public:

  DistSTO_lock_args(const DistSTO_lock_args&);
  DistSTO_lock_args& operator=(const DistSTO_lock_args&);
  DistSTO_lock_args() : tuid(0), may_duplicate_items_(0) {
  }

  virtual ~DistSTO_lock_args() throw();
  int32_t tuid;
  std::vector<std::string>  titems;
  bool may_duplicate_items_;
  std::vector<bool>  preceding_duplicate_read_;

  _DistSTO_lock_args__isset __isset;

  void __set_tuid(const int32_t val);

  void __set_titems(const std::vector<std::string> & val);

  void __set_may_duplicate_items_(const bool val);

  void __set_preceding_duplicate_read_(const std::vector<bool> & val);

  bool operator == (const DistSTO_lock_args & rhs) const
  {
    if (!(tuid == rhs.tuid))
      return false;
    if (!(titems == rhs.titems))
      return false;
    if (!(may_duplicate_items_ == rhs.may_duplicate_items_))
      return false;
    if (!(preceding_duplicate_read_ == rhs.preceding_duplicate_read_))
      return false;
    return true;
  }
  bool operator != (const DistSTO_lock_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DistSTO_lock_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DistSTO_lock_pargs {
 public:


  virtual ~DistSTO_lock_pargs() throw();
  const int32_t* tuid;
  const std::vector<std::string> * titems;
  const bool* may_duplicate_items_;
  const std::vector<bool> * preceding_duplicate_read_;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _DistSTO_lock_result__isset {
  _DistSTO_lock_result__isset() : success(false) {}
  bool success :1;
} _DistSTO_lock_result__isset;

class DistSTO_lock_result {
 public:

  DistSTO_lock_result(const DistSTO_lock_result&);
  DistSTO_lock_result& operator=(const DistSTO_lock_result&);
  DistSTO_lock_result() : success(0) {
  }

  virtual ~DistSTO_lock_result() throw();
  int64_t success;

  _DistSTO_lock_result__isset __isset;

  void __set_success(const int64_t val);

  bool operator == (const DistSTO_lock_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const DistSTO_lock_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DistSTO_lock_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _DistSTO_lock_presult__isset {
  _DistSTO_lock_presult__isset() : success(false) {}
  bool success :1;
} _DistSTO_lock_presult__isset;

class DistSTO_lock_presult {
 public:


  virtual ~DistSTO_lock_presult() throw();
  int64_t* success;

  _DistSTO_lock_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _DistSTO_check_args__isset {
  _DistSTO_check_args__isset() : tuid(false), titems(false), may_duplicate_items_(false), preceding_duplicate_read_(false) {}
  bool tuid :1;
  bool titems :1;
  bool may_duplicate_items_ :1;
  bool preceding_duplicate_read_ :1;
} _DistSTO_check_args__isset;

class DistSTO_check_args {
 public:

  DistSTO_check_args(const DistSTO_check_args&);
  DistSTO_check_args& operator=(const DistSTO_check_args&);
  DistSTO_check_args() : tuid(0), may_duplicate_items_(0) {
  }

  virtual ~DistSTO_check_args() throw();
  int32_t tuid;
  std::vector<std::string>  titems;
  bool may_duplicate_items_;
  std::vector<bool>  preceding_duplicate_read_;

  _DistSTO_check_args__isset __isset;

  void __set_tuid(const int32_t val);

  void __set_titems(const std::vector<std::string> & val);

  void __set_may_duplicate_items_(const bool val);

  void __set_preceding_duplicate_read_(const std::vector<bool> & val);

  bool operator == (const DistSTO_check_args & rhs) const
  {
    if (!(tuid == rhs.tuid))
      return false;
    if (!(titems == rhs.titems))
      return false;
    if (!(may_duplicate_items_ == rhs.may_duplicate_items_))
      return false;
    if (!(preceding_duplicate_read_ == rhs.preceding_duplicate_read_))
      return false;
    return true;
  }
  bool operator != (const DistSTO_check_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DistSTO_check_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DistSTO_check_pargs {
 public:


  virtual ~DistSTO_check_pargs() throw();
  const int32_t* tuid;
  const std::vector<std::string> * titems;
  const bool* may_duplicate_items_;
  const std::vector<bool> * preceding_duplicate_read_;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _DistSTO_check_result__isset {
  _DistSTO_check_result__isset() : success(false) {}
  bool success :1;
} _DistSTO_check_result__isset;

class DistSTO_check_result {
 public:

  DistSTO_check_result(const DistSTO_check_result&);
  DistSTO_check_result& operator=(const DistSTO_check_result&);
  DistSTO_check_result() : success(0) {
  }

  virtual ~DistSTO_check_result() throw();
  bool success;

  _DistSTO_check_result__isset __isset;

  void __set_success(const bool val);

  bool operator == (const DistSTO_check_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const DistSTO_check_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DistSTO_check_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _DistSTO_check_presult__isset {
  _DistSTO_check_presult__isset() : success(false) {}
  bool success :1;
} _DistSTO_check_presult__isset;

class DistSTO_check_presult {
 public:


  virtual ~DistSTO_check_presult() throw();
  bool* success;

  _DistSTO_check_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _DistSTO_install_args__isset {
  _DistSTO_install_args__isset() : tuid(false), tid(false), write_values(false) {}
  bool tuid :1;
  bool tid :1;
  bool write_values :1;
} _DistSTO_install_args__isset;

class DistSTO_install_args {
 public:

  DistSTO_install_args(const DistSTO_install_args&);
  DistSTO_install_args& operator=(const DistSTO_install_args&);
  DistSTO_install_args() : tuid(0), tid(0) {
  }

  virtual ~DistSTO_install_args() throw();
  int32_t tuid;
  int64_t tid;
  std::vector<std::string>  write_values;

  _DistSTO_install_args__isset __isset;

  void __set_tuid(const int32_t val);

  void __set_tid(const int64_t val);

  void __set_write_values(const std::vector<std::string> & val);

  bool operator == (const DistSTO_install_args & rhs) const
  {
    if (!(tuid == rhs.tuid))
      return false;
    if (!(tid == rhs.tid))
      return false;
    if (!(write_values == rhs.write_values))
      return false;
    return true;
  }
  bool operator != (const DistSTO_install_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DistSTO_install_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DistSTO_install_pargs {
 public:


  virtual ~DistSTO_install_pargs() throw();
  const int32_t* tuid;
  const int64_t* tid;
  const std::vector<std::string> * write_values;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DistSTO_install_result {
 public:

  DistSTO_install_result(const DistSTO_install_result&);
  DistSTO_install_result& operator=(const DistSTO_install_result&);
  DistSTO_install_result() {
  }

  virtual ~DistSTO_install_result() throw();

  bool operator == (const DistSTO_install_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const DistSTO_install_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DistSTO_install_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DistSTO_install_presult {
 public:


  virtual ~DistSTO_install_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _DistSTO_abort_args__isset {
  _DistSTO_abort_args__isset() : tuid(false) {}
  bool tuid :1;
} _DistSTO_abort_args__isset;

class DistSTO_abort_args {
 public:

  DistSTO_abort_args(const DistSTO_abort_args&);
  DistSTO_abort_args& operator=(const DistSTO_abort_args&);
  DistSTO_abort_args() : tuid(0) {
  }

  virtual ~DistSTO_abort_args() throw();
  int32_t tuid;

  _DistSTO_abort_args__isset __isset;

  void __set_tuid(const int32_t val);

  bool operator == (const DistSTO_abort_args & rhs) const
  {
    if (!(tuid == rhs.tuid))
      return false;
    return true;
  }
  bool operator != (const DistSTO_abort_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DistSTO_abort_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DistSTO_abort_pargs {
 public:


  virtual ~DistSTO_abort_pargs() throw();
  const int32_t* tuid;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DistSTO_abort_result {
 public:

  DistSTO_abort_result(const DistSTO_abort_result&);
  DistSTO_abort_result& operator=(const DistSTO_abort_result&);
  DistSTO_abort_result() {
  }

  virtual ~DistSTO_abort_result() throw();

  bool operator == (const DistSTO_abort_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const DistSTO_abort_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DistSTO_abort_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DistSTO_abort_presult {
 public:


  virtual ~DistSTO_abort_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class DistSTOClient : virtual public DistSTOIf {
 public:
  DistSTOClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  DistSTOClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  void do_rpc(DoRpcResponse& _return, const int64_t objid, const int64_t op, const std::vector<std::string> & opargs);
  void send_do_rpc(const int64_t objid, const int64_t op, const std::vector<std::string> & opargs);
  void recv_do_rpc(DoRpcResponse& _return);
  int64_t lock(const int32_t tuid, const std::vector<std::string> & titems, const bool may_duplicate_items_, const std::vector<bool> & preceding_duplicate_read_);
  void send_lock(const int32_t tuid, const std::vector<std::string> & titems, const bool may_duplicate_items_, const std::vector<bool> & preceding_duplicate_read_);
  int64_t recv_lock();
  bool check(const int32_t tuid, const std::vector<std::string> & titems, const bool may_duplicate_items_, const std::vector<bool> & preceding_duplicate_read_);
  void send_check(const int32_t tuid, const std::vector<std::string> & titems, const bool may_duplicate_items_, const std::vector<bool> & preceding_duplicate_read_);
  bool recv_check();
  void install(const int32_t tuid, const int64_t tid, const std::vector<std::string> & write_values);
  void send_install(const int32_t tuid, const int64_t tid, const std::vector<std::string> & write_values);
  void recv_install();
  void abort(const int32_t tuid);
  void send_abort(const int32_t tuid);
  void recv_abort();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class DistSTOProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<DistSTOIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (DistSTOProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_do_rpc(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_lock(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_check(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_install(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_abort(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  DistSTOProcessor(boost::shared_ptr<DistSTOIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &DistSTOProcessor::process_ping;
    processMap_["do_rpc"] = &DistSTOProcessor::process_do_rpc;
    processMap_["lock"] = &DistSTOProcessor::process_lock;
    processMap_["check"] = &DistSTOProcessor::process_check;
    processMap_["install"] = &DistSTOProcessor::process_install;
    processMap_["abort"] = &DistSTOProcessor::process_abort;
  }

  virtual ~DistSTOProcessor() {}
};

class DistSTOProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  DistSTOProcessorFactory(const ::boost::shared_ptr< DistSTOIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< DistSTOIfFactory > handlerFactory_;
};

class DistSTOMultiface : virtual public DistSTOIf {
 public:
  DistSTOMultiface(std::vector<boost::shared_ptr<DistSTOIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~DistSTOMultiface() {}
 protected:
  std::vector<boost::shared_ptr<DistSTOIf> > ifaces_;
  DistSTOMultiface() {}
  void add(boost::shared_ptr<DistSTOIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  void do_rpc(DoRpcResponse& _return, const int64_t objid, const int64_t op, const std::vector<std::string> & opargs) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->do_rpc(_return, objid, op, opargs);
    }
    ifaces_[i]->do_rpc(_return, objid, op, opargs);
    return;
  }

  int64_t lock(const int32_t tuid, const std::vector<std::string> & titems, const bool may_duplicate_items_, const std::vector<bool> & preceding_duplicate_read_) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->lock(tuid, titems, may_duplicate_items_, preceding_duplicate_read_);
    }
    return ifaces_[i]->lock(tuid, titems, may_duplicate_items_, preceding_duplicate_read_);
  }

  bool check(const int32_t tuid, const std::vector<std::string> & titems, const bool may_duplicate_items_, const std::vector<bool> & preceding_duplicate_read_) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->check(tuid, titems, may_duplicate_items_, preceding_duplicate_read_);
    }
    return ifaces_[i]->check(tuid, titems, may_duplicate_items_, preceding_duplicate_read_);
  }

  void install(const int32_t tuid, const int64_t tid, const std::vector<std::string> & write_values) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->install(tuid, tid, write_values);
    }
    ifaces_[i]->install(tuid, tid, write_values);
  }

  void abort(const int32_t tuid) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->abort(tuid);
    }
    ifaces_[i]->abort(tuid);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class DistSTOConcurrentClient : virtual public DistSTOIf {
 public:
  DistSTOConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  DistSTOConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  int32_t send_ping();
  void recv_ping(const int32_t seqid);
  void do_rpc(DoRpcResponse& _return, const int64_t objid, const int64_t op, const std::vector<std::string> & opargs);
  int32_t send_do_rpc(const int64_t objid, const int64_t op, const std::vector<std::string> & opargs);
  void recv_do_rpc(DoRpcResponse& _return, const int32_t seqid);
  int64_t lock(const int32_t tuid, const std::vector<std::string> & titems, const bool may_duplicate_items_, const std::vector<bool> & preceding_duplicate_read_);
  int32_t send_lock(const int32_t tuid, const std::vector<std::string> & titems, const bool may_duplicate_items_, const std::vector<bool> & preceding_duplicate_read_);
  int64_t recv_lock(const int32_t seqid);
  bool check(const int32_t tuid, const std::vector<std::string> & titems, const bool may_duplicate_items_, const std::vector<bool> & preceding_duplicate_read_);
  int32_t send_check(const int32_t tuid, const std::vector<std::string> & titems, const bool may_duplicate_items_, const std::vector<bool> & preceding_duplicate_read_);
  bool recv_check(const int32_t seqid);
  void install(const int32_t tuid, const int64_t tid, const std::vector<std::string> & write_values);
  int32_t send_install(const int32_t tuid, const int64_t tid, const std::vector<std::string> & write_values);
  void recv_install(const int32_t seqid);
  void abort(const int32_t tuid);
  int32_t send_abort(const int32_t tuid);
  void recv_abort(const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
