/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef DistSTO_CONSTANTS_H
#define DistSTO_CONSTANTS_H

#include "DistSTO_types.h"



class DistSTOConstants {
 public:
  DistSTOConstants();

};

extern const DistSTOConstants g_DistSTO_constants;



#endif
